apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: {{ .Values.namespace.name }}-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    cert-manager.io/issuer: "jenkins-prod-issuer"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nhq.id.vn
    secretName: crs-tls
  rules:
  - host: nhq.id.vn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.namespace.name }}-service
            port:
              number: 32000