apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: jenkins-prod-issuer
  namespace: {{ .Values.namespace.name }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: pin30227@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: jenkins-prod-issuer
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx